services:
  finca-la-carla-backend:
    build: ./backend
    container_name: hotel-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  frontend:
    build: ./frontend
    container_name: hotel-frontend
    ports:
      - "80:80"
    depends_on:
      - finca-la-carla-backend
    restart: always
