services:
  # Backend Web Service
  - type: web
    name: finca-la-carla-backend
    runtime: docker
    dockerContext: backend
    dockerFilePath: ../Dockerfile.backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default

  # Frontend Web Service (serving via Nginx)
  - type: web
    name: finca-la-carla-frontend
    runtime: docker
    dockerContext: frontend
    dockerFilePath: ../Dockerfile.frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        value: http://finca-la-carla-backend:8080
